package com.G19.hospital.DTO.inventory;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SupplierDto {
    // You can include supplierId if it's a business field; otherwise, it might be autogenerated.
    private Long supplierId;
    private String name;
    private String email;
    private String contactDetails;
    private String address;
}
